Iter9
tritonol/metrics-collecting pull request #12
Opened 2023-08-29 08:14 UTC by tritonol

2023-08-30 19:53 UTC, connorholt commented on internal/middleware/compressor/gzip.go
> +func GzipMiddleware(next http.Handler) http.Handler {
В задании написано, 
Функция сжатия должна работать для контента с типами application/json и text/html.
нужно добавить проверку

2023-08-30 19:53 UTC, connorholt commented on cmd/server/main.go
> +	if cfg.Backup.Restore {
логика restore и SaveMetricsToFile не должна быть в main, представь что у тебя появился крон или воркер (т,е новый main пакет) который тоже использует хранилище и там должна быть такая логика, ее придется туда копировать руками. Как я это вижу, есть два варианта решения либо сделать два хранилища - одно inMemory как было в первом инкремента а второе с файлом, и внутри есть эта логика при том что оба хранилища могут реализовывать один интерфейс. Тогда будет само хранилище знать про restart и save, либо второй вариант оставить одно хранилище и сделать еще одну абстракцию которая взаимодействует с ним и тогда этот код можно будет переиспользовать. В следующем спринте еще появится база данных, подумай как сдеать чтобы ее можно было проще сюда внедрить

2023-08-30 19:53 UTC, connorholt commented on internal/routes/routes.go
> +	r.Get("/", get.MainPage(storage))
на подумать, можно хендлеры сделать как структуры и в них явно передать зависмости в main, в принципе если роутер разрастается его можно тоже заполнить в main, и тогда 

```

type MainHandler struct {
	storage metricGetter
}

func (h *MainHandler) MainPage(w http.ResponseWriter, r *http.Request) {
		resp := make([]string, 0, 50)
		for k, v := range h.storage.GetAllGauge() {
			resp = append(resp, fmt.Sprintf("%s: %f", k, v))
		}
		for k, v := range h.storage.GetAllCounter() {
			resp = append(resp, fmt.Sprintf("%s: %d", k, v))
		}

		render.HTML(w, r, strings.Join(resp, "\n"))
	}
}
```
в main.go
```
....
mainHandler := get.NewMainHandler(storage)
```
а использование в роутере будет такое
```
...
r.Get("/", mainHandler.MainPage)
```

2023-08-30 19:53 UTC, connorholt commented on internal/routes/routes.go
> +	r.Get("/", get.MainPage(storage))
и handler можно в будущем замокать и протестировать

2023-08-30 19:53 UTC, connorholt commented on internal/backup/backup.go
> +func SaveMetricsPeriodically(interval int64, filePath string, mg metricGetter) {
не используется

2023-10-27 15:39 UTC, edylcrm requested changes

2023-10-27 15:39 UTC, edylcrm commented on cmd/server/main.go
Комментарии разделены на несколько типов:
[BLOCKER] - Проблема, не решив которую принять работу нельзя
[LINT] - Заменичение, опционально к выполнению
[FYI] - просто ремарка

2023-10-27 15:39 UTC, edylcrm commented on cmd/server/main.go
> +	err := http.ListenAndServe(cfg.Server.Address, routes.MetricRouter(storage, logger))
[FYI] Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-27 15:39 UTC, edylcrm commented on internal/backup/backup.go
> +func SaveMetricsPeriodically(interval int64, filePath string, mg metricGetter) {
[BLOCKER] Давай все методы/файлы которые не используются удалим

2023-10-27 15:39 UTC, edylcrm commented on internal/backup/backupManager.go
> +	sigCh := make(chan os.Signal, 1)
[LINT] По поводу обработки сигналов обсудили 1-1, тут смотри сам выносить это в main или нет, я бы вынес и завязался на context

2023-10-27 15:39 UTC, edylcrm commented on internal/agent/request/sendmetric.go
> +func sendJSONMetrics(serverAddress, mtype, mname string, mvalue interface{}) {
[BLOCKER] sendMetric - метод не используется, давай удалим

2023-10-27 15:39 UTC, edylcrm commented on internal/backup/backupManager.go
> +			os.Exit(0)
[BLOCKER] завершать все приложение в отдельной горутине не стоит. Лучше это делать явно в "главной" горутине в func main() {} в main.go

2023-10-27 15:39 UTC, edylcrm commented on internal/server/handlers/metrics/get/get.go
> +		if (err != nil) {
[LINT] Здесь () не нужны

2023-10-27 15:39 UTC, edylcrm commented on internal/storage/memstorage/memstorage.go
> +type MemStorage struct {
[LINT] здесь тоже 1-1 обсудили как сделать лучше. Так же на твое усмотрение.

2023-11-03 05:39 UTC, edylcrm requested changes

2023-11-03 05:39 UTC, edylcrm commented on cmd/server/main.go
> +		logger.Fatal("", zap.Error(err))
[BLOCKER] Здесь тогда тоже нужно вызвать cancel() или получится так, что если http serve по какой-то причине не поднялся приложение будет ждать завершения работы backupManager

2023-11-07 07:22 UTC, edylcrm approved these changes

2023-11-13 12:16 UTC, merged